### ISSUE TITLE
Readme example running in SEGFAULT

### ISSUE THREAD

**Issue by meetme2meat** [jasonroelofs/rice#107]
I was trying on of the README.md example 

```#include "rice/Class.hpp"
  #include "rice/String.hpp"

  using namespace Rice;

  Object test_initialize(Object self)
  {
    self.iv_set("@foo", 42);
  }

  Object test_hello(Object /* self */)
  {
    String str("hello, world");
    return str;
  }

  extern "C"
  void Init_test()
  {
    Class rb_cTest =
      define_class("Test")
      .define_method("initialize", &test_initialize)
      .define_method("hello", &test_hello);
  }
```

The make runs sucessfully (except for the warning) 

but running the above code in ruby result in segmentation fault. 
```ruby
2.4.3 :002 > $:.unshift(Dir.pwd)
2.4.3 :003 > require 'test'
 => true
2.4.3 :004 > Test.new
(irb):4: [BUG] Segmentation fault at 0xfffffffffffffffc
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0102 e:000101 CFUNC  :initialize
c:0020 p:---- s:0099 e:000098 CFUNC  :new
c:0019 p:0012 s:0095 e:000094 EVAL   (irb):4 [FINISH]
c:0018 p:---- s:0092 e:000091 CFUNC  :eval
c:0017 p:0025 s:0084 e:000083 METHOD /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/workspace.rb:87
c:0016 p:0027 s:0076 e:000074 METHOD /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/context.rb:381
c:0015 p:0024 s:0069 e:000068 BLOCK  /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:493
c:0014 p:0041 s:0060 e:000059 METHOD /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:627
c:0013 p:0011 s:0054 e:000053 BLOCK  /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:490
c:0012 p:0128 s:0049 e:000048 BLOCK  /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:246 [FINISH]
c:0011 p:---- s:0045 e:000044 CFUNC  :loop
c:0010 p:0009 s:0041 e:000040 BLOCK  /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:232 [FINISH]
c:0009 p:---- s:0038 e:000037 CFUNC  :catch
c:0008 p:0018 s:0033 e:000032 METHOD /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:231
c:0007 p:0037 s:0029 E:0025d0 METHOD /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:489
c:0006 p:0008 s:0025 e:000024 BLOCK  /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:430 [FINISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :catch
c:0004 p:0075 s:0017 E:000028 METHOD /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:429
c:0003 p:0118 s:0012 e:000011 METHOD /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:385
c:0002 p:0023 s:0006 e:000005 EVAL   /Users/werain/.rvm/rubies/ruby-2.4.3/bin/irb:11 [FINISH]
c:0001 p:0000 s:0003 E:002070 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/werain/.rvm/rubies/ruby-2.4.3/bin/irb:11:in `<main>'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:385:in `start'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:429:in `run'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:429:in `catch'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb:493:in `block (2 levels) in eval_input'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/context.rb:381:in `evaluate'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
(irb):4:in `irb_binding'
(irb):4:in `new'
(irb):4:in `initialize'

-- Machine register context ------------------------------------------------
 rax: 0xfffffffffffffffc rbx: 0x00007ffee9d5e7c0 rcx: 0x0000000000000008
 rdx: 0xffffffffffffffcc rdi: 0x00007ffee9d5e7c0 rsi: 0x00007fc985406a70
 rbp: 0x00007ffee9d5e5b8 rsp: 0x00007ffee9d5e5a8  r8: 0x00007fc98790c870
  r9: 0x000000000007d881 r10: 0x0840160312001020 r11: 0x0000003564957cb0
 r12: 0x00000001063da5b0 r13: 0x00007ffee9d5e7c0 r14: 0x00007ffee9d5e784
 r15: 0x00007fc9854069e8 rip: 0x00000001063da5bd rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------
0   libruby.2.4.3.dylib                 0x000000010607eef7 rb_vm_bugreport + 135
1   libruby.2.4.3.dylib                 0x0000000105f111f8 rb_bug_context + 472
2   libruby.2.4.3.dylib                 0x0000000105ff74b8 sigsegv + 72
3   libsystem_platform.dylib            0x00007fff71b44f5a _sigtramp + 26
4   test.bundle                         0x00000001063da5bd _ZN4Rice6detail15Ruby_Function_1ImPFmiEiE4callEPS4_ + 13
5   libruby.2.4.3.dylib                 0x0000000105f1b23a rb_protect + 250
6   test.bundle                         0x00000001063e3beb _ZN4Rice6detail7protectEPFmmEm + 27
7   test.bundle                         0x00000001063da13f _ZN4Rice6Object6iv_setIiEEvNS_10IdentifierERKT_ + 47

-- Other runtime information -----------------------------------------------

* Loaded script: irb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/x86_64-darwin17/enc/encdb.bundle
    5 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/x86_64-darwin17/enc/trans/transdb.bundle
    6 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/unicode_normalize.rb
    7 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/x86_64-darwin17/rbconfig.rb
    8 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/compatibility.rb
    9 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/defaults.rb
   10 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/deprecate.rb
   11 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/errors.rb
   12 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/version.rb
   13 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/requirement.rb
   14 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/platform.rb
   15 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/basic_specification.rb
   16 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/stub_specification.rb
   17 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/util/list.rb
   18 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/x86_64-darwin17/stringio.bundle
   19 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/rfc2396_parser.rb
   20 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/rfc3986_parser.rb
   21 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/common.rb
   22 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/generic.rb
   23 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/ftp.rb
   24 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/http.rb
   25 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/https.rb
   26 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/ldap.rb
   27 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/ldaps.rb
   28 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri/mailto.rb
   29 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/uri.rb
   30 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb
   31 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/exceptions.rb
   32 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/util.rb
   33 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/bundler_version_finder.rb
   34 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb
   35 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   36 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/monitor.rb
   37 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   38 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems.rb
   39 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/rubygems/path_support.rb
   40 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/version.rb
   41 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/core_ext/name_error.rb
   42 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/levenshtein.rb
   43 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/jaro_winkler.rb
   44 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checker.rb
   45 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/delegate.rb
   46 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   47 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   48 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   49 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   50 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/null_checker.rb
   51 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean/formatter.rb
   52 /Users/werain/.rvm/gems/ruby-2.4.3@global/gems/did_you_mean-1.1.0/lib/did_you_mean.rb
   53 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/e2mmap.rb
   54 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/init.rb
   55 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/workspace.rb
   56 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/inspector.rb
   57 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/output-method.rb
   58 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/context.rb
   59 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/extend-command.rb
   60 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/notifier.rb
   61 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/slex.rb
   62 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-token.rb
   63 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ruby-lex.rb
   64 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/src_encoding.rb
   65 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/magic-file.rb
   66 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/x86_64-darwin17/readline.bundle
   67 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/input-method.rb
   68 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/locale.rb
   69 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb.rb
   70 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/completion.rb
   71 /Users/werain/.rvm/scripts/irbrc.rb
   72 /Users/werain/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/irb/ext/save-history.rb
   73 /Users/werain/Documents/ruby-ccplus/test.bundle

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

Abort trap: 6
```

Ruby Version `2.4.3`
Rice version `2.1.2`
g++ version 
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jasonroelofs** [comment]
Thanks for the report. I will make some time to check this out and see what's going on.

**Comment by cfis** [comment]
This works fine on master, so going to close.
