### ISSUE TITLE
TruffleRuby support

### ISSUE THREAD

**Issue by mtortonesi** [jasonroelofs/rice#189]
In my quest of getting torch.rb to work, have been trying to build rice on top of TruffleRuby (truffleruby+graalvm-23.0.0 installed with rbenv+ruby-build on my M1 Mac) but I ran into some linking issues:

```
...
  "_ruby_init_loadpath", referenced from:
      fixture__Address_Registration_Guard__setup() in lto.o
      fixture_Array_setup() in lto.o
      fixture_Attribute_setup() in lto.o
      fixture__Builtin_Object__setup() in lto.o
      fixture_Class_setup() in lto.o
      fixture_Array_setup() (.263) in lto.o
      fixture__Data_Object__setup() in lto.o
      ...
  "_ruby_sysinit", referenced from:
      fixture__Address_Registration_Guard__setup() in lto.o
      fixture_Array_setup() in lto.o
      fixture_Attribute_setup() in lto.o
      fixture__Builtin_Object__setup() in lto.o
      fixture_Class_setup() in lto.o
      fixture_Array_setup() (.263) in lto.o
      fixture__Data_Object__setup() in lto.o
      ...
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [unittest] Error 1
rake aborted!
Failed
/Users/mauro/code/test/truffleruby/rice/rakefile:12:in `block in run_command'
/Users/mauro/code/test/truffleruby/rice/rakefile:8:in `run_command'
/Users/mauro/code/test/truffleruby/rice/rakefile:33:in `block (3 levels) in <top (required)>'
<internal:core> core/dir.rb:321:in `chdir'
/Users/mauro/code/test/truffleruby/rice/rakefile:31:in `block (2 levels) in <top (required)>'
<internal:core> core/kernel.rb:381:in `load'
Tasks: TOP => build => /Users/mauro/code/test/truffleruby/
```

And that is even after I manually changed CMakeLists.txt to include header dirs and library files:

```
  target_include_directories (unittest PRIVATE "/Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/cext/include")
  target_include_directories (unittest PRIVATE "/Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/llvm/include")
  target_link_libraries (unittest "/Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/cext/librubysignal.dylib")
  target_link_libraries (unittest "/Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/cext/libtruffleruby.dylib")
  target_link_libraries (unittest "/Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/cext/libtruffleposix.dylib")
```

I am rather lost at the moment. Do you have any ideas / suggestions on how to move on from here?

**Comment by jasonroelofs** [comment]
I would be rather surprised if this worked. Rice is pretty strongly linked to how Ruby itself is implemented, and makes at least one or two internal calls (e.g. `rb_frame_method_id_and_class`). So you would need to find an alternate to this method in the TruffleRuby C API, and even then I have no idea if it would work at all. 

Or, to put it shortly, only MRI is supported.

**Comment by mtortonesi** [comment]
I am wondering if I could add to truffleruby the internal calls that rice requires. I started looking into it, but got a compilation problem. I submitted an issue: oracle/truffleruby#3357. I will keep you posted.

**Comment by mtortonesi** [comment]
FYI, I just submitted oracle/truffleruby#3363, that implements the rb_frame_method_and_id in Truffleruby. The patch seems to get rice, and in turn torch.rb, to work with Truffleruby.
