### ISSUE TITLE
dir_config don't work

### ISSUE THREAD

**Issue by vintikzzz** [jasonroelofs/rice#63]
I have code in my extconf.rb
```ruby
require "mkmf-rice"

HEADER_DIRS = [
  '/opt/local/include',
  '/usr/local/include',
  '/usr/include',
]

LIB_DIRS = [
  '/opt/local/lib',
  '/usr/local/lib',
  '/usr/lib',
]

dir_config('', HEADER_DIRS, LIB_DIRS)
COMPILE_CXX << ' -DBOOST_ASIO_DYN_LINK=1'
have_library("torrent-rasterbar") or raise
have_library("boost_system") or raise
create_makefile('torrent_client')
```

and while compilling it fails on
```ruby
have_library("torrent-rasterbar") or raise
```
```
MacBook-Pro-Pavel:video-torrent-info vintik$ rake clean && rake compile --trace
Failed to remove tmp/x86_64-darwin12.4.0/stage: No such file or directory - tmp/x86_64-darwin12.4.0/stage
** Invoke compile (first_time)
** Invoke compile:x86_64-darwin12.4.0 (first_time)
** Invoke compile:torrent_client:x86_64-darwin12.4.0 (first_time)
** Invoke copy:torrent_client:x86_64-darwin12.4.0:2.0.0 (first_time)
** Invoke lib (first_time, not_needed)
** Invoke tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/torrent_client.bundle (first_time)
** Invoke tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/Makefile (first_time)
** Invoke tmp/x86_64-darwin12.4.0/torrent_client/2.0.0 (first_time)
** Execute tmp/x86_64-darwin12.4.0/torrent_client/2.0.0
mkdir -p tmp/x86_64-darwin12.4.0/torrent_client/2.0.0
** Invoke ext/torrent_client/extconf.rb (first_time, not_needed)
** Execute tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/Makefile
cd tmp/x86_64-darwin12.4.0/torrent_client/2.0.0
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/bin/ruby -I. ../../../../ext/torrent_client/extconf.rb
checking for main() in -ltorrent-rasterbar... no
*** ../../../../ext/torrent_client/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=../../../../ext/torrent_client
	--curdir
	--ruby=/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/bin/ruby
	--with-libpath
	--without-libpath
	--with--dir
	--without--dir
	--with--include
	--without--include=${-dir}/include
	--with--lib
	--without--lib=${-dir}/
	--with-torrent-rasterbarlib
	--without-torrent-rasterbarlib
../../../../ext/torrent_client/extconf.rb:23:in `<main>': unhandled exception
rake aborted!
Command failed with status (1): [/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/...]
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils.rb:54:in `block in create_shell_runner'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils.rb:45:in `call'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils.rb:45:in `sh'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/gems/rake-compiler-0.9.2/lib/rake/extensiontask.rb:188:in `block (2 levels) in define_compile_tasks'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils_ext.rb:37:in `chdir'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/gems/rake-compiler-0.9.2/lib/rake/extensiontask.rb:185:in `block in define_compile_tasks'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:234:in `call'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:234:in `block in execute'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `load'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `<main>'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => compile => compile:x86_64-darwin12.4.0 => compile:torrent_client:x86_64-darwin12.4.0 => copy:torrent_client:x86_64-darwin12.4.0:2.0.0 => tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/torrent_client.bundle => tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/Makefile
```
When i switch back to standard 'mkmf' all libraries become available, except "rice"
```
Failed to remove tmp/x86_64-darwin12.4.0/stage: No such file or directory - tmp/x86_64-darwin12.4.0/stage
** Invoke compile (first_time)
** Invoke compile:x86_64-darwin12.4.0 (first_time)
** Invoke compile:torrent_client:x86_64-darwin12.4.0 (first_time)
** Invoke copy:torrent_client:x86_64-darwin12.4.0:2.0.0 (first_time)
** Invoke lib (first_time, not_needed)
** Invoke tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/torrent_client.bundle (first_time)
** Invoke tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/Makefile (first_time)
** Invoke tmp/x86_64-darwin12.4.0/torrent_client/2.0.0 (first_time)
** Execute tmp/x86_64-darwin12.4.0/torrent_client/2.0.0
mkdir -p tmp/x86_64-darwin12.4.0/torrent_client/2.0.0
** Invoke ext/torrent_client/extconf.rb (first_time, not_needed)
** Execute tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/Makefile
cd tmp/x86_64-darwin12.4.0/torrent_client/2.0.0
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/bin/ruby -I. ../../../../ext/torrent_client/extconf.rb
checking for main() in -ltorrent-rasterbar... yes
checking for main() in -lboost_system... yes
creating Makefile
cd -
** Execute tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/torrent_client.bundle
cd tmp/x86_64-darwin12.4.0/torrent_client/2.0.0
make
compiling ../../../../ext/torrent_client/torrent_client.cpp
../../../../ext/torrent_client/torrent_client.cpp:8:10: fatal error: 'rice/Class.hpp' file not found
#include "rice/Class.hpp"
         ^
1 error generated.
make: *** [torrent_client.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils.rb:54:in `block in create_shell_runner'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils.rb:45:in `call'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils.rb:45:in `sh'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/gems/rake-compiler-0.9.2/lib/rake/extensiontask.rb:152:in `block (2 levels) in define_compile_tasks'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/file_utils_ext.rb:37:in `chdir'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/gems/rake-compiler-0.9.2/lib/rake/extensiontask.rb:151:in `block in define_compile_tasks'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/vintik/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `load'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `<main>'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/vintik/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => compile => compile:x86_64-darwin12.4.0 => compile:torrent_client:x86_64-darwin12.4.0 => copy:torrent_client:x86_64-darwin12.4.0:2.0.0 => tmp/x86_64-darwin12.4.0/torrent_client/2.0.0/torrent_client.bundle
```
I haven't dig deep into the code yet, but I think it somehow ignores dir_config method

**Comment by jasonroelofs** [comment]
If this is still an issue, please open a new ticket.
